"""Weekly report generation.

Pulls the last `window_days` of findings from the knowledge base, has the LLM
write a concise executive summary, and renders both plain-text and HTML email
bodies. Deliberately concise — highlights what needs attention, no fluff.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from datetime import date

from .config import Config
from .llm import BaseLLM, LLMError
from .store import Finding, KnowledgeStore


@dataclass
class Report:
    subject: str
    executive_summary: str
    findings: list[Finding]
    text_body: str
    html_body: str
    finding_count: int
    summary_is_fallback: bool = False


def _group(findings: list[Finding]) -> dict[str, dict[str, list[Finding]]]:
    """competitor -> category -> [findings]"""
    grouped: dict[str, dict[str, list[Finding]]] = defaultdict(lambda: defaultdict(list))
    for f in findings:
        grouped[f.competitor][f.category].append(f)
    return grouped


def _summary_prompt(cfg: Config, findings: list[Finding]) -> str:
    lines = [
        f"- [{f.competitor} / {cfg.category_label(f.category)}] {f.title}: {f.summary}"
        for f in findings
    ]
    joined = "\n".join(lines)
    return f"""You are writing the executive summary for {cfg.company_name}'s weekly
competitor-intelligence briefing. Below are this week's raw findings.

Write 4-7 tight bullet points highlighting ONLY what leadership needs to pay
attention to: the most strategically significant moves, patterns across
competitors, and anything that could affect {cfg.company_name}. Be concise and
factual. No preamble, no filler, no restating every item. Output plain bullets
starting with "- ".

Findings:
{joined}"""


def _render_text(cfg: Config, summary: str, grouped, week_of: str) -> str:
    out = [
        f"{cfg.company_name} — Weekly Competitor Watch",
        f"Week of {week_of}",
        "=" * 48,
        "",
        "EXECUTIVE SUMMARY",
        "-" * 17,
        summary.strip() or "(no significant developments this week)",
        "",
    ]
    for competitor in sorted(grouped):
        out.append(f"\n### {competitor}")
        for category in cfg.category_keys:
            items = grouped[competitor].get(category)
            if not items:
                continue
            out.append(f"  {cfg.category_label(category)}:")
            for f in items:
                date_str = f" ({f.event_date})" if f.event_date else ""
                out.append(f"    • {f.title}{date_str}")
                out.append(f"      {f.summary}")
                if f.source_url:
                    out.append(f"      Source: {f.source_url}")
        out.append("")
    out.append("-" * 48)
    out.append(f"Generated by the {cfg.company_name} Competitor Intelligence Agent.")
    return "\n".join(out)


def _render_html(cfg: Config, summary: str, grouped, week_of: str) -> str:
    def esc(s: str) -> str:
        return (
            s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        )

    summary_html = "".join(
        f"<li>{esc(line[2:].strip())}</li>"
        for line in summary.splitlines()
        if line.strip().startswith("-")
    ) or "<li>No significant developments this week.</li>"

    sections = []
    for competitor in sorted(grouped):
        cat_html = []
        for category in cfg.category_keys:
            items = grouped[competitor].get(category)
            if not items:
                continue
            li = []
            for f in items:
                date_str = f" <span style='color:#888'>({esc(f.event_date)})</span>" if f.event_date else ""
                src = (
                    f" <a href='{esc(f.source_url)}' style='color:#2563eb;text-decoration:none'>[source]</a>"
                    if f.source_url
                    else ""
                )
                li.append(
                    f"<li style='margin-bottom:8px'><b>{esc(f.title)}</b>{date_str}{src}"
                    f"<br><span style='color:#444'>{esc(f.summary)}</span></li>"
                )
            cat_html.append(
                f"<div style='margin:8px 0'><span style='font-size:13px;font-weight:600;"
                f"color:#6b7280;text-transform:uppercase;letter-spacing:.04em'>"
                f"{esc(cfg.category_label(category))}</span>"
                f"<ul style='margin:6px 0 0;padding-left:20px'>{''.join(li)}</ul></div>"
            )
        sections.append(
            f"<div style='margin:22px 0;padding:16px;border:1px solid #e5e7eb;border-radius:10px'>"
            f"<h3 style='margin:0 0 6px;color:#111827'>{esc(competitor)}</h3>"
            f"{''.join(cat_html)}</div>"
        )

    return f"""<div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
      max-width:680px;margin:0 auto;color:#111827">
  <div style="border-bottom:3px solid #2563eb;padding-bottom:10px;margin-bottom:16px">
    <h1 style="margin:0;font-size:22px">{esc(cfg.company_name)} — Weekly Competitor Watch</h1>
    <div style="color:#6b7280;font-size:14px">Week of {esc(week_of)}</div>
  </div>
  <div style="background:#f8fafc;border-radius:10px;padding:16px;margin-bottom:8px">
    <div style="font-weight:700;margin-bottom:6px">Executive Summary</div>
    <ul style="margin:0;padding-left:20px">{summary_html}</ul>
  </div>
  {''.join(sections)}
  <div style="color:#9ca3af;font-size:12px;margin-top:20px;border-top:1px solid #e5e7eb;padding-top:10px">
    Generated automatically by the {esc(cfg.company_name)} Competitor Intelligence Agent.
  </div>
</div>"""


def _fallback_summary(cfg: Config, grouped) -> str:
    """A no-LLM summary: one bullet per competitor, so the email still ships
    even when the model is rate-limited or unavailable."""
    lines = []
    for competitor in sorted(grouped):
        cats = grouped[competitor]
        count = sum(len(v) for v in cats.values())
        # Lead with the first finding's title as the headline for this competitor.
        first = next(iter(next(iter(cats.values()))))
        extra = f" (+{count - 1} more)" if count > 1 else ""
        lines.append(f"- {competitor}: {first.title}{extra}")
    return "\n".join(lines)


def build_report(cfg: Config, llm: BaseLLM, store: KnowledgeStore) -> Report:
    findings = store.recent_findings(cfg.report_window_days)
    week_of = date.today().isoformat()
    grouped = _group(findings)

    fallback = False
    if not findings:
        summary = "- No new competitor developments were recorded this week."
    else:
        try:
            summary = llm.generate(_summary_prompt(cfg, findings)).text
        except LLMError:
            # Don't let a summary failure block delivery — ship a basic summary.
            summary = _fallback_summary(cfg, grouped)
            fallback = True

    subject = (
        f"{cfg.report_subject_prefix} Week of {week_of} — "
        f"{len(findings)} update{'s' if len(findings) != 1 else ''}"
    )
    return Report(
        subject=subject,
        executive_summary=summary,
        findings=findings,
        text_body=_render_text(cfg, summary, grouped, week_of),
        html_body=_render_html(cfg, summary, grouped, week_of),
        finding_count=len(findings),
        summary_is_fallback=fallback,
    )
